# version: '3.8'

# services:
#   backend:
#     image: new-backend-server-backend
#     context: shonaz_backend_server
#     container_name: shonaz-backend
#     ports:
#       - "4000:4000"
#     depends_on:
#       - mongo
#       - redis

#   frontend:
#     image: shonaz-frontend-image
#     context: shonaz_frontend_server
#     container_name: shonaz-frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend

#   mongo:
#     image: mongo
#     container_name: mongo-container
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

#   redis:
#     image: redis
#     container_name: redis-container
#     ports:
#       - "6379:6379"

# volumes:
#   mongo-data:
